<?php

/**
 * Helper function to map objects to their values to be used in templates.
 *
 * @param string $object_id
 *   The ID of the object for which to produce a list of values.
 *
 * @return array
 *   An associative array of values, including:
 *   - label: A string containing object's label.
 *   - class: A string containing an HTML class to add to markup representing
 *     the object.
 *   - link: A string containing a textual HTML link to the object.
 *   - thumb: A string containing an image HTML link to the object.
 *   - description: A string containing a description of the object.
 *   - pid: The object's PID.
 */
function pld_collections_objects_object_mapper($object_id) {

  $o = islandora_object_load($object_id);
  $medium_size = $o->getDatastream('MEDIUM_SIZE');
  $url = "islandora/object/{$object_id}";
  $module_path = drupal_get_path('module', 'islandora');

  $parent = arg(2);
  $parent = islandora_object_load($parent);
  $parent = $parent->label;

   $obj_models = $o->relationships->get('info:fedora/fedora-system:def/model#', 'hasModel');
   $obj_model = $obj_models[0]['object']['value'];
    
   $copyright = $o->getDatastream('COPYRIGHT');

   $no_thumb_path = drupal_get_path('theme', 'pld');
   $no_thumb_path = $no_thumb_path .'/img/no_image_available.png';
   
   $current_object = arg(2);


  if($current_object == 'islandora:root') {
	  $img = array(
	    '#theme' => 'image',
	    '#path' => ($o && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $o['TN']) ?
	      "$url/datastream/TN/view" :
	     $no_thumb_path),
	    '#attributes' => array(),
	  );
  }
  
  if($medium_size != FALSE) {

  	$img = array(
	    '#theme' => 'image',
	    '#path' => ($o && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $o['MEDIUM_SIZE']) ?
	      "$url/datastream/MEDIUM_SIZE/view" :
	     $no_thumb_path),
	    '#attributes' => array(),
	  );
  } 

 if($obj_model == 'islandora:compoundCModel') {
      $parts = islandora_compound_object_get_parts($o->id);
      $obj_count = count($parts);
      
  if($obj_count <= 0) {
     $img = array(
	    '#theme' => 'image',
	    '#path' =>  $no_thumb_path,
	    '#attributes' => array(),
	  );

 } else {

    $first_child = $parts[0];
    $child_obj = islandora_object_load($first_child);
 
    $img = array(
	    '#theme' => 'image',
	    '#path' => ($child_obj && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $child_obj['MEDIUM_SIZE']) ?
	      "islandora/object/".$first_child."/datastream/MEDIUM_SIZE/view" :
	      $no_thumb_path),
	    '#attributes' => array(),
	  );
      }
   }

   if($obj_model == 'islandora:pageCModel') {
    $img = array(
      '#theme' => 'image',
      '#path' => ($o && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $o['JPG']) ?
        "$url/datastream/JPG/view" :
       $no_thumb_path),
    '#attributes' => array(),
    );
   }

   if($copyright != FALSE):
    $copyright_path = drupal_get_path('theme', 'pld') .'/img/image_under_copyright.png';
   $img = array(
    '#theme' => 'image',
    '#path' => $copyright_path,
    '#attributes' => array(),
   );
   endif;
  
  $img = drupal_render($img);



  if($o) {
  	$link_options = array('html' => TRUE, 'attributes' => array('title' => $o->label));
  	$description = NULL;
  	if( isset($o['DC']) && islandora_datastream_access(ISLANDOR_VIEW_OBJECTS, $o['DC'] ) ) {
  		$dc = DublinCore::importFromXMLString($o['DC']->content);
  		if($dc) {
  			$dc = $dc->asArray();
  			$description = $dc['dc:description']['value'];
  		}
  	}

  	return array(
  		'label' => $o->label,
  		'class' => drupal_strtolower(preg_replace('/[^A-Za-z0-9]/', '-', $o->id)),
  		'link' => l($o->label, $url, $link_options),
  		'thumb' => l($img, $url, $link_options),
  		'description' => $description,
  		'pid' => $o->id,
      'parent' => $parent,
  	);
  	
  }

}

function pld_collections_preprocess_islandora_objects_subset(&$variables) {

	$display = (empty($_GET['display'])) ? $variables['display'] : $_GET['display'];
	$grid_display = $display == 'grid';
	$list_display = !$grid_display;

	$query_params = drupal_get_query_parameters($_GET);

	$variables['content']['#objects'] = array_map('pld_collections_objects_object_mapper', $variables['content']['#objects']);

}

function pld_collections_menu_alter(&$menu) {
   if(isset($menu['islandora/object/%islandora_object/pages'])) {
   $menu['islandora/object/%islandora_object/pages']['page callback'] = 'pld_collections_islandora_book_pages_menu';
  }
}

function pld_collections_islandora_book_pages_menu(AbstractObject $object) {
  module_load_include('inc', 'islandora', 'includes/breadcrumb');
  drupal_set_breadcrumb(islandora_get_breadcrumbs($object));
  module_load_include('inc', 'islandora_paged_content', 'includes/utilities');
  $pages = islandora_paged_content_get_pages($object);
  return theme('islandora_objects_subset', array('objects' => array_keys($pages)));
}
?>